export const TermsService = `
**Pangolin Terms of Service and Disclaimer**

Last updated: 1 November 2023

**Terms of Service**

Welcome to [https://app.pangolin.exchange](https://app.pangolin.exchange/), a website-hosted user interface (the "Interface" or "App") that is managed and supported by Pangolin Inc ("we", "our", or "us"). The Interface provides access to a decentralized system on the Pangolin protocol ("the Pangolin Protocol" or the "Protocol") that allows users to trade, stake, make offerings of and otherwise use digital assets built on the Avalanche Network using the tools and functionality available on the App.

This Terms of Service Agreement (the "Agreement") explains the terms and conditions by which you may access and use the Interface. You must read this Agreement carefully. By accessing or using the Interface, you signify that you have read, understand, and agree to be bound by this Agreement in its entirety. If you do not agree, you are not authorized to access or use the Interface and should not use the Interface.

1. **Eligibility**

To access or use the Interface, you must be able to form a legally binding contract with us. Accordingly, you represent that you are at least the age of majority in your jurisdiction (e.g. eighteen years old) and have the full right, power, and authority to enter into and comply with the terms and conditions of this Agreement on behalf of yourself and any company or legal entity for which you may access or use the Interface. You further represent that you are not a citizen, resident, or member of the Cayman Islands or any jurisdiction or group that is subject to economic sanctions by the United States, the European Union, Australia or the United Kingdom. You also agree that you will not use the Interface where your use of the Interface would be illegal or otherwise violate any applicable law. You further represent that your access and use of the Interface and your conduct with respect to such access and use will fully comply with all applicable laws and regulations, and that you will not access or use the Interface to conduct, promote, or otherwise facilitate any illegal activity.

2. **Prohibited Activity**

You agree not to engage in, or attempt to engage in, any of the following categories of prohibited activity in relation to your access and use of the Interface:

- **Intellectual Property Infringement**. This is activity that infringes on or violates any copyright, trademark, service mark, patent, right of publicity, right of privacy, or other proprietary or intellectual property rights under the law.
- **Cyberattack**. Activity that seeks to interfere with or compromise the integrity, security, or proper functioning of the Interface, the Protocol or of any computer, server, network, personal device, or other information technology system, including (but not limited to) the deployment of viruses and denial of service attacks.
- **Fraud and Misrepresentation**. Activity that seeks to defraud us or any other person or entity, including (but not limited to) providing any false, inaccurate, or misleading information in order to unlawfully obtain the property of another.
- **Market Manipulation**. Activity that violates any applicable law, rule, or regulation concerning the integrity of trading markets, including (but not limited to) the manipulative tactics commonly known as spoofing and wash trading.
- **Securities and Derivatives Violations or Insider Trading**. Activity that violates any applicable law, rule, or regulation concerning the trading of securities or derivatives including (without limitation) any prohibitions on use of non-public information to gain personal advantage.
- **Any Other Unlawful Conduct**. Activity that violates any applicable law, rule, or regulation of the United States, the European Union, Australia or the United Kingdom or another relevant jurisdiction, including (but not limited to) the restrictions and regulatory requirements imposed by such countries.

3. **No Warranties** 

The Interface is provided on an "AS IS" and "AS AVAILABLE" basis. To the fullest extent permitted by law, we disclaim any representations and warranties of any kind, whether express, implied, or statutory, including (but not limited to) the warranties of merchantability and fitness for a particular purpose. You acknowledge and agree that your use of the Interface is at your own risk. We do not represent or warrant that access to the Interface will be continuous, uninterrupted, error-free, timely, or secure; that the information contained in the Interface will be accurate, reliable, complete, or current; or that the Interface will be free from errors, defects, viruses, or other harmful elements. No advice, information, or statement that we make should be treated as creating any warranty concerning the Interface. We do not endorse, guarantee, or assume responsibility for any advertisements, offers, or statements made by third parties concerning the Interface.

4. **No Professional Advice**

All information and public statements on the Interface or otherwise made by us or our officers, directors, employees, contractors, agents, affiliates, or subsidiaries is for informational purposes only and should not be construed as financial, legal or professional advice. You should not take, or refrain from taking, any action based on any such information or statements. Before you make any financial, legal, or other decisions involving the Interface, you should seek independent professional advice from an individual who is licensed and qualified in the area for which such advice would be appropriate.

5. **Assumption of Risk**

By accessing and using the Interface, you represent that you understand the inherent risks associated with using cryptographic and blockchain-based systems, and that you have a working knowledge of the usage and intricacies of digital assets such as bitcoin (BTC), AVAX, Ethereum (ETH) and other digital tokens such as those following the ERC-20 standard. You further understand that the markets for these digital assets are highly volatile due to factors including (but not limited to) adoption, speculation, technology, security, and regulation. You acknowledge and accept that the cost and speed of transacting with cryptographic and blockchain-based systems such as Avalanche is variable and may increase dramatically at any time. You further acknowledge and accept the risk that your digital assets may lose some or all of their value while they are supplied to the Protocol through the Interface, you may suffer loss (including without limitation divergence risk and "impermanent loss") due to the fluctuation of prices of tokens in a trading pair or liquidity pool, and, especially in expert modes, experience significant price slippage and cost. You understand that anyone can create a token, including fake versions of existing tokens and tokens that falsely claim to represent projects, and acknowledge and accept the risk that you may mistakenly trade those or other tokens. You further acknowledge that we do not vet, qualify, audit, endorse or support tokens accessible via the Interface. By using the Interface, you confirm that you have considered and accept the risks associated with the purchase of cryptocurrencies and the use of public blockchains, including (without limitation) the following risks:
- Impermanent loss and divergence risk caused by the operation of the constant function market-maker algorithm. This algorithm rebalances digital asset pairs in response to price fluctuations and can cause you to suffer loss even when one of the digital assets in the pair is increasing in price;
- the market in which you are trading is not active or liquid;
- your trades materially and adversely affecting the market price in which you are participating;
- negative publicity that adversely affects prices;
- defects in the AVAX Protocol or cryptocurrency;
- your private keys wallet being (a) lost, resulting in permanent and irretrievable loss of funds; or (b) compromised, resulting in the misappropriation of the your funds by malicious third parties;
- the loss of users, validators and nodes to an extent that results in failure of the Interface or Protocol to operate as intended;
- a third party issuing digital assets similar or identical to those available through the Interface, resulting in a loss of users, validators or nodes or drop in prices; or
- the creation of a hard fork in the blockchain which renders your cryptocurrencies invalid or otherwise unable to function in accordance with their intended design and purpose.
We are not responsible for any of these variables or risks, do not own or control the Protocol or the digital assets created on it, and cannot be held liable for any resulting losses that you experience while accessing or using the Interface. Accordingly, you understand and agree to assume full responsibility for all of the risks of accessing and using the Interface to interact with the Protocol.

6. **Third-Party Resources and Promotions**

The Interface may contain references or links to third-party resources, including (but not limited to) information, materials, products, or services, that we do not own or control. In addition, third parties may offer promotions related to your access and use of the Interface. These links are provided for informational purposes only. We do not endorse or assume any responsibility for any such resources or promotions. If you access any such resources or participate in any such promotions, you do so at your own risk, and you understand that this Agreement does not apply to your dealings or relationships with any third parties. You expressly relieve us of any and all liability arising from your use of any such resources or participation in any such promotions and will look solely and exclusively towards such third parties to seek redress.

7. **Additional Rights.**

We reserve the following rights, which do not constitute obligations of ours: (a) with or without notice to you, to modify, substitute, eliminate or add to the Interface; (b) to review, modify, filter, disable, delete and remove any and all content and information from the Interface; and (c) to cooperate with any law enforcement, court or government investigation or order or third party requesting or directing that we disclose information or content or information that you provide.

8. **Privacy**

We care about your privacy. When you use the Interface, the only information we receive is the token names or identifiers of the tokens that you swap. We do not collect any personally identifiable information ("PII") from you (e.g. AVAX address, IP address, or transaction amounts) unless you choose to send this information to us. When you use the Interface, you are interacting with the AVAX blockchain, which is a publicly available blockchain that provides transparency into your transactions and interactions with the blockchain. We do not control and are not responsible for any information you make public on the AVAX blockchain by taking actions through the Interface.For more information, please refer to Pangolin&#39;s privacy policy and cookie policy.

9. **Proprietary Rights**

We own all intellectual property and other rights in the Interface and its contents, including (but not limited to) software, text, images, trademarks, service marks, copyrights, patents, and designs. Unlike the Interface, the Protocol is comprised almost entirely of open-source or source-available software running on the public Avalanche blockchain. Where elements of the Protocol are licensed by us or third parties, the terms of such licences will be disclosed on Pangolin&#39;s GitHub page: [https://github.com/pangolindex](https://github.com/pangolindex) and you agree, as a condition of using the Interface, to comply with the terms of such licences.

10. **Indemnity**

You agree to hold harmless, release, defend, and indemnify us and our officers, directors, employees, contractors, agents, affiliates, and subsidiaries from and against all claims, damages, obligations, losses, liabilities, costs, and expenses arising from: (a) your access and use of the Interface and Protocol; (b) your violation of any term or condition of this Agreement, the right of any third party, or any other applicable law, rule, or regulation; and (c) any other party&#39;s access and use of the Interface with your assistance or using any device or account that you own, manage or control.

11. **Limitation of Liability**

The Interface and Protocol are supplied "as-is" and, to the maximum extent permitted by law, without warranties of any kind, whether express or implied. We assume no liability or responsibility for any: (a) errors, mistakes, or inaccuracies of content; (b) personal injury or property damage, of any nature whatsoever, resulting from any access or use of the Interface; (c) unauthorized access or use of any secure server or database in our control, or the use of any information or data stored therein; (d) interruption or cessation of function related to the Interface; (e) bugs, viruses, trojan horses, or the like that may be transmitted to or through the Interface; (f) errors or omissions in, or loss or damage incurred as a result of the use of, any content made available through the Interface; and (g) the defamatory, offensive, or illegal conduct of any third party. Under no circumstances shall we or any of our officers, directors, employees, contractors, agents, affiliates, or subsidiaries be liable to you for any claims, proceedings, liabilities, obligations, damages, losses, or costs in an amount exceeding the amount you paid to us in exchange for access to and use of the Interface, or $100.00, whichever is lesser. This limitation of liability applies regardless of whether the alleged liability is based on contract, tort, negligence, strict liability, under an indemnity or any other basis, and even if we have been advised of the possibility of such liability, loss or damage. Under no circumstances shall we or any of our officers, directors, employees, contractors, agents, affiliates, or subsidiaries be liable to you for any indirect, punitive, incidental, special, consequential, or exemplary damages, including (but not limited to) damages for loss of revenue, profits, savings, goodwill, use, data, or other intangible property, arising out of or relating to any access or use of the Interface or Protocol, nor will we be responsible for any damage, loss, or injury resulting from hacking, tampering, or other unauthorized access or use of the Protocol, the Interface or the information contained within it. Some jurisdictions do not allow the exclusion of certain warranties or the limitation or exclusion of certain liabilities and damages. To the extent that any provision of this Agreement is held to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions will not in any way be affected or impaired, and such provision will be deemed to be restated to reflect the original intent as nearly as possible in accordance with applicable law.

12. **Force Majeure**

Notwithstanding anything to the contrary in this Agreement and to the maximum extent permitted by law, we will not be in breach of this Agreement, or liable to you, for failure to perform any of our obligations under this Agreement caused, or contributed to, by any event or circumstance beyond our control (each, a "Force Majeure Event"), including, without limitation, acts or omissions by you or third parties, natural disasters, riots, war, civil disorder, court orders, acts or regulations of governmental bodies, labour disputes or failures or fluctuations in electrical power, heat, light, air conditioning or telecommunications equipment or lines, or other equipment failure.

13. **Release of Claims**

You expressly agree that you assume all risks in connection with your access and use of the Interface and your interaction with the Protocol. You further expressly waive and release us and our officers, directors, employees, contractors, agents, affiliates, and subsidiaries from any and all liability, claims, causes of action, or damages arising from or in any way relating to your use of the Interface and your interaction with the Protocol. If you are a California resident, you waive the benefits and protections of California Civil Code § 1542, which provides: "[a] general release does not extend to claims that the creditor or releasing party does not know or suspect to exist in his or her favor at the time of executing the release and that, if known by him or her, would have materially affected his or her settlement with the debtor or released party."

14. **Dispute Resolution**

We will use our best efforts to resolve any potential disputes through informal, good faith negotiations. If a potential dispute arises, you must contact us by sending an email to [legal@pangolin.exchange](mailto:legal@pangolin.exchange) so that we can attempt to resolve it without resorting to formal dispute resolution. If we aren&#39;t able to reach an informal resolution within sixty days of your email, then you and we both agree to resolve the potential dispute according to the process set forth below.Any claim or controversy arising out of or relating to the Interface, this Agreement, or any other acts or omissions for which you may contend that we are liable, including (but not limited to) any claim or controversy as to arbitrability ("Dispute"), shall be finally and exclusively settled by arbitration under the Arbitration Act 2013. You understand that you are required to resolve all Disputes by binding arbitration. The arbitration shall be held on a confidential basis before a single arbitrator, who shall be selected pursuant to Arbitration Act 2013. The arbitration will be held in Cayman Islands, unless you and we both agree to hold it elsewhere. Unless we agree otherwise, the arbitrator may not consolidate your claims with those of any other party. Any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction.

15. **No Fiduciary Duties**

This Agreement is not intended to, and does not, create or impose any fiduciary or agency duties on us. To the fullest extent permitted by law, you acknowledge and agree that we owe no fiduciary or agent duties or liabilities to you or any other party, and that to the extent any such duties or liabilities may exist at law or in equity, those duties and liabilities are hereby irrevocably disclaimed, waived, and eliminated. You further agree that the only duties and obligations that we owe you are those set out expressly in this Agreement.

16. **Modification of this Agreement**

We reserve the right, in our sole discretion, to modify this Agreement from time to time. If we make any modifications, we will notify you by updating the date at the top of the Agreement and by maintaining a current version of the Agreement at [https://github.com/pangolindex/interface](https://github.com/pangolindex/interface). All modifications will be effective when they are posted, and your continued accessing or use of the Interface will serve as confirmation of your acceptance of those modifications. If you do not agree with any modifications to this Agreement, you must immediately stop accessing and using the Interface.

17. **Class Action and Jury Trial Waiver**

You must bring any and all Disputes against us in your individual capacity and not as a plaintiff in or member of any purported class action, collective action, private attorney general action, or other representative proceeding. This provision applies to class arbitration. You and we both agree to waive the right to demand a trial by jury.

18. **GoverningLaw**

You agree that the laws of the Cayman Islands, without regard to principles of conflict of laws, govern this Agreement and any Dispute between you and us. You further agree that the Interface shall be deemed to be based solely in the Cayman Islands, and that although the Interface may be available in other jurisdictions, its availability does not give rise to general or specific personal jurisdiction in any forum outside the Cayman Islands. You agree that Cayman Islands is the proper forum for any appeals of an arbitration award or for court proceedings in the event that this Agreement&#39;s binding arbitration clause is found to be unenforceable.

19. **Entiregreement.**

The Terms constitute the entire agreement between you and us with respect to the subject matter hereof. The Terms supersede any and all prior or contemporaneous writtenand oral agreements, communications and other understandings—if any—relating to the subject matter of the Terms.
`
